"use strict";
// Assignment Operators
let c = 10;
c += 5;
console.log(c);
let xy = 22;
xy += 2;
console.log(xy);
let aliPocketMoney = 200;
let spend = 120;
let left = aliPocketMoney - spend;
left += 23;
console.log(left);
let result = 34;
result -= 4;
console.log(result);
let ab = 78;
let cd = 60;
let sum = ab + cd;
sum += 2;
console.log(sum);
